# Generated by Django 4.2 on 2023-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("hood-001", "후드 1"),
                            ("hood-002", "후드 2"),
                            ("hood-003", "후드 3"),
                            ("jean-001", "청바지 1"),
                            ("jean-002", "청바지 2"),
                            ("jean-003", "청바지 3"),
                            ("socks", "양말"),
                            ("cap", "모자"),
                        ],
                        max_length=10,
                        verbose_name="제품 코드",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="제품명")),
                ("description", models.CharField(max_length=50, verbose_name="설명")),
                ("price", models.IntegerField(default=0, verbose_name="가격")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("F", "Free"),
                        ],
                        max_length=1,
                        verbose_name="사이즈",
                    ),
                ),
            ],
        ),
    ]
